import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './features/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        error: '#ba1a1a',
        'surface-container-highest': '#e0e3e5',
        'tertiary-fixed': '#6bff8f',
        'on-primary-container': '#7c839b',
        'on-tertiary-fixed': '#002109',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#009844',
        'on-secondary-container': '#745c00',
        outline: '#76777d',
        'secondary-fixed': '#ffe088',
        secondary: '#735c00',
        'surface-bright': '#f7f9fb',
        'tertiary-container': '#002109',
        'surface-dim': '#d8dadc',
        surface: '#f7f9fb',
        'primary-container': '#131b2e',
        'inverse-on-surface': '#eff1f3',
        'secondary-fixed-dim': '#e9c349',
        'surface-container': '#eceef0',
        'on-error-container': '#93000a',
        'on-surface': '#191c1e',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#241a00',
        'primary-fixed': '#dae2fd',
        'secondary-container': '#fed65b',
        'inverse-primary': '#bec6e0',
        'on-surface-variant': '#45464d',
        'on-primary-fixed-variant': '#3f465c',
        primary: '#000000',
        'outline-variant': '#c6c6cd',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#bec6e0',
        'surface-container-low': '#f2f4f6',
        tertiary: '#000000',
        'on-secondary': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'on-tertiary': '#ffffff',
        background: '#f7f9fb',
        'on-secondary-fixed-variant': '#574500',
        'surface-tint': '#565e74',
        'on-tertiary-fixed-variant': '#005321',
        'on-background': '#191c1e',
        'tertiary-fixed-dim': '#4ae176',
        'on-primary-fixed': '#131b2e',
        'surface-variant': '#e0e3e5',
        'inverse-surface': '#2d3133',
      },
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};

export default config;
